#!/bin/sh

start() {
  if ! pgrep -f $1 ;
  then
    $@&
  fi 
}

# music
start mpd
start mpDris2 # add playerctl support to mpd

# compositor
start picom --experimental-backends --config $HOME/.config/awesome/theme/picom.conf

# auth


# load X colors
start xrdb $HOME/.Xresources
